version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p1a_py_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped